# Generated by Django 4.2.25 on 2025-10-14 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="created_by",
        ),
    ]
